name: MAA
description: An app to make lives of pregnent women easier

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1
  flutter_sparkline: any
  flutter_staggered_grid_view: any 
  google_maps_flutter: ^0.4.0
  fluttery_seekbar: ^0.0.1
flutter:

  uses-material-design: true

  assets:
      - assets/login_logo.png
      - assets/shoes1.png
      - assets/focus.jpeg
      - assets/images/logo.png
      - assets/images/powered_by.png
      - assets/images/email_icon.png
      - assets/images/password_icon.png
      - assets/images/user_icon.png
      - assets/images/as.png



  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
    - family: Nexa
      fonts:
        - asset: assets/Nexa-Bold.otf

    - family: NexaLight
      fonts:
        - asset: assets/Nexa-Light.otf
